Sofie-Automation/sofie-mos-connection

- .circleci/config.yml
When renaming, one of the commands were accidentialy renamed to
captial case.
> fix: typo in send coverage command

- .circleci/config.yml
Yarn times out when publishing. Adding a larger network-timeout
Yarn publish fails due to timeout
Yarn should hopefully not fail again.
> fix: yarn timeout

- .circleci/config.yml
- CHANGES.md
Just some minor changes to make the config more generic, and for me to remember more in detail what to do when applying to next projects.
> fix: use generic project name in config. Add more steps to do

- src/MosConnection.ts
- src/MosDevice.ts
- src/__tests__/MosConnection.spec.ts
- src/__tests__/MosDevice.spec.ts
- src/config/connectionConfig.ts
- src/connection/NCSServerConnection.ts
- src/connection/mosSocketClient.ts
_Note: This is not ready to merge yet!_
This PR introduces a new feature, and related fixes, called "Buddy Server" which allows the MOS connection to keep functioning when one server goes down.
When the primary server disconnects (either through closing the socket or not responding in due time) this will switch the connection to the secondary server and resend the message(s). As per the MOS Spec the connection is switched back to Primary when the connection with the Buddy Server is lost or a NACK is sent by the Secondary server.
_Note: optionally an off spec behaviour is defined where the connection is switched back to Primary whenever the connection with the Primary server is reestablished._
> Buddy Server / Failover to secondary

- src/mosModel/Parser.ts
Bug fix
Error getting techDescription from undefined.
No exception will be raised.
Just a small fix. When 'o' is a string, Object.keys(xmlPath.o).length is counting the string length, and then o.attributes.techDescription raises a error because o.attributes does not exists.
> Parser fix for techDescription error

- src/MosConnection.ts
- src/api.ts
- src/connection/NCSServerConnection.ts
- src/connection/Server.ts
This PR adds an optional option to `connectionOptions.dontUseQueryPort` which causes the library to not try to connect to the "query port".
The motivation for this is that I've noticed that some servers doesn't expose that port, which causes that connection to fail repeatedly, flooding the logs with errors, even though the other functions still work fine.
> Feature:dont use query port

- src/api.ts
Imports MosDuration from `dataTypes/mosDuration.ts` as MosDurationDataType in `api.ts`
MosDuration is imported and then redefined as type MosDuration = MosDuration. 
Redefinition of MosDuration within `api.ts` is avoided.
> fix: resolve an issue with a duplicated type MosDuration

- src/mosModel/Parser.ts
When calling a roStoryReplace the editorial start and duration values can be 0
When calling a roStoryReplace the editorial start and duration values will be ignored if set to 0.
> fix: editorial start and duration can be 0

- src/MosConnection.ts
- src/__tests__/MosDevice.spec.ts
- src/connection/NCSServerConnection.ts
- src/connection/mosSocketClient.ts
Feature.
Too much logging information. Duplication of logging emitted and sent to the console.
Debug flag should be set to false to switch of console logging. Changes ensure all valuable information is emitted.
Related to https://github.com/nrkno/tv-automation-mos-gateway/pull/26
> Reduce the amount of logging information in production

- src/MosConnection.ts
- src/__mocks__/socket.ts
- src/__tests__/MosConnection.spec.ts
- src/__tests__/MosDevice.spec.ts
- src/__tests__/__snapshots__/MosConnection.spec.ts.snap
- src/__tests__/testData.spec.ts
- src/connection/Server.ts
- src/connection/mosMessageParser.ts
- src/connection/mosSocketClient.ts
- src/connection/socketConnection.ts
- src/dataTypes/mosString128.ts
- src/mosModel/Parser.ts
Bug fix
Related to #55 
Messages can be split across multiple tcp packets.
When receiving each packet, any whitespace is trimmed. This could be desired whitespace in the middle of a sentance.
Additionally, the packet handling looks like it expects the <mos> and </mos> tags to lie perfectly at the start and end of packets, which is not guaranteed. If they do not, then this will cause the parsing to fail on a message and not handle it
`_dataChunks` is now used better as a rolling buffer. All received packets are appended to it, and then multiple iterations are done to …
> fix: rewrite mos message chunk parsing (v0.x)

- packages/helper/src/mosModel/__tests__/profile2.spec.ts
- packages/helper/src/mosModel/profile2/ROAck.ts
- packages/helper/src/mosModel/profile2/xmlConversion.ts
- packages/model/src/model.ts
Feature
Items of Stories are not being list when sending a `RoAck` message.
Each item of each story of the `RoAck` message is being listed. 
> [ADD] List Items in RoAck Message

- packages/connector/src/__mocks__/socket.ts
- packages/connector/src/__tests__/MosConnection.spec.ts
- packages/connector/src/__tests__/lib.ts
- packages/connector/src/connection/mosSocketClient.ts
This PR makes a change to the handover logic such that any heartbeat messages will be left in the queue on the specific MOS socket.
This fixes an issue where the primary would never connect _if_ the buddy was up _and_ a command was sent through the mos connection such that a handover was performed.
> Fix: primary down upon first connect

- packages/connector/src/MosDevice.ts
Bug fix
When a roElementAction of types Insert or Replace for Stories receives multiple stories in the element_source, it sends a type to the callback that was not expected.
In this operation, if the parsed element_source is an array, pass the array as a parameter. If it's not an array, build an array with the element_source value.
It could be nice to have a test to check the change
> allow_multiple_stories_in_roElementAction_Replace_&_Insert

- .github/workflows/audit.yaml
- .github/workflows/node.yaml
- commonPackage.json
- package.json
- packages/connector/package.json
- packages/examples/package.json
- packages/helper/package.json
- packages/model/package.json
- packages/quick-mos/package.json
re-adds scripts for auditing dependencies.
Scripts for auditing dependencies where missing after the v3.0.0 refactoring
> chore: re-add audit dependencies

- packages/connector/src/__mocks__/testData.ts
- packages/connector/src/__tests__/Profile4.spec.ts
- packages/connector/src/__tests__/__snapshots__/Profile4.spec.ts.snap
- packages/helper/src/mosModel/profile4/xmlConversion.ts
Bug Fix
When the following message is received:
```
<mos>
<mosID>mosID</mosID>
<ncsID>ncsID</ncsID>
<messageID>messageId</messageID>
<roStorySend>
<roID>roID</roID>
<storyID>story 0</storyID>
<storySlug>My Story</storySlug>
<storyNum/>
<storyBody>
<storyItem>
<itemID>item0</itemID>
<itemSlug/>
<objID/>
<mosID/>
<itemTrigger>CHAINED</itemTrigger>
</storyItem>
</storyBody>
</roStorySend>
</mos>
```
The parser will not parse the content correctly and will not follow the definition of the Interface IMOSItem
Parse the StoryItem with `XMLMosItem.fromXML(item, strict)` …
> fix: case roStorySend one storyItem

- packages/connector/src/MosConnection.ts
- packages/connector/src/__tests__/MessageChunking.spec.ts
- packages/connector/src/__tests__/lib.ts
- packages/connector/src/connection/mosMessageParser.ts
This PR is opened on behalf of the NRK
This is a bug fix to the issue described in #83 
If an incoming message contains a `</mos>` tag, the message is cut off and parsed at that point. This causes wierdness internally in mos-connection, including a circular mos-object.
The message parser looks for matching pairs of `<mos>` and `</mos>` tags, so messages aren't cut of prematurely anymore.
`npm install @mos-connection/connector@3.0.5-nightly-fix-multiple-mos-tags-20231214-120351-59cacb2.0`
* Verify that the fix for #83 works.
* Normal regression testing
> Multiple <mos> and </mos> tags in messages

- packages/connector/src/MosDevice.ts
- packages/connector/src/__mocks__/testData.ts
- packages/connector/src/__tests__/Profile2.spec.ts
- packages/connector/src/__tests__/__snapshots__/Profile2.spec.ts.snap
This PR is posted on behald of the NRK.
This can be considered a bug fix. It adds support for a few missing MOS messages, that should have been there from the start.
This doesn't affect the consumer-side API of the library.
As reported in #86 and #57, if, for example, a `<roStoryReplace>` message is received, the library will emit the error `"Unsupported function"`.
While these types of messages are considered deprecated_ they should still be supported.
Quote from the mos protocol documentation:
>At present, applications and devices claiming support for MOS v2.8.5 Profile 2 must support all of these messages for backwards compatibility plus the functionally equivalent <[roElementAction](https://mosprotocol.com/wp-content/MOS-Protocol-Documents/MOS_Protocol_Version_2.8.5_Final.htm#roElement …
> fix: Add support for receiving roStoryX, roItemY messages (SOFIE-2858)

- packages/connector/src/MosDevice.ts
- packages/connector/src/__tests__/Profile0.spec.ts
- packages/connector/src/__tests__/Profile1.spec.ts
- packages/connector/src/__tests__/Profile2.spec.ts
- packages/connector/src/__tests__/__snapshots__/Profile1.spec.ts.snap
- packages/connector/src/__tests__/api.spec.ts
- packages/connector/src/api.ts
This pull request is posted by me on behalf of SuperFly.tv.
This is a: 
**BREAKING** Feature 
Disclaimer: To be honest, I think that the mos protocol spec is a tad unclear on how this REALLY should work, but I believe that this is how it _should be_. Ref: [Mos Protocol; mosReqAll](https://mosprotocol.com/wp-content/MOS-Protocol-Documents/MOS-Protocol-2.8.4-Current.htm#mosReqAll).
Currently, when `mosDevice.sendRequestAllMOSObjects()` is called, a `<mosReqAll>` message is sent, and a `<mosListAll>` is expected as a reply.
This is not according to the spec, since there should be a  [mosAck](https://mosprotocol.com/wp-content/MOS-Protocol-Documents/MOS-Protocol-2.8.4-Current.htm#mosAck), followed (_asynchronously on the other server initiated lower socket, I believe_) by …
> fix!: proper support for Profile 1 <mosReqAll>, <mosObj> and <mosListAll> (SOFIE-2890)

- packages/connector/src/__mocks__/testData.ts
- packages/connector/src/__tests__/Profile0-open-media.spec.ts
- packages/connector/src/__tests__/__snapshots__/Profile0-open-media.spec.ts.snap
- packages/helper/src/mosModel/profile0/xmlConversion.ts
- packages/model/src/model.ts
- packages/model/src/mosTypes/mosTime.ts
This pull request is posted on behalf of BBC
This is a: 
Bug fix
If the NRCS has empty or missing objects in the MachineInfo, the mos-connection will return an error, also in non strict mode.
When in non strict mode, mos-connection will fill out empty empty objects, and handle xmlSupportedProfiles as optional if it's undefined.
Run the MOS gateway with OpenMedia, and it will crash with the old version of mos-connection.
- [ x] PR is ready to be reviewed.
- [ x] The functionality has been tested by the author.
> fix: NRCS returns empty objects

- packages/connector/src/MosConnection.ts
- packages/connector/src/__tests__/Profile0-non-strict.spec.ts
- packages/connector/src/__tests__/__snapshots__/Profile0-non-strict.spec.ts.snap
- packages/connector/src/__tests__/lib.ts
- packages/connector/src/connection/NCSServerConnection.ts
- packages/connector/src/connection/mosSocketClient.ts
This PR is posted on behalf of CBC/Radio-Canada
This is a: 
Feature
Relates to [issue 94](https://github.com/nrkno/sofie-mos-connection/issues/94). Message without messageId would cause the connection status to be "Bad - Primary: No heartbeats on upper"
In non-strict mode, the messageId will be the last sent message id, if the message is a \<heartbeat> or a \<regMachInfo>.
Tested with a MOS Gateway using MOS protocol 2.8 (with no messageId), and by checking/unchecking the (Optional) Strict MOS data handling checkbox in the MOS Gateway config. A test is provided as well in the packages/connector/src/__tests__/Profile0-non-strict.spec.ts file.
> feat: support for no messageId in non-strict mode

- packages/helper/src/__tests__/parsing/mosSample3.json
- packages/helper/src/__tests__/parsing/mosSample3.xml
- packages/helper/src/__tests__/parsing/mosXml2Js.spec.ts
This PR is made on behalf of BBC
This is a test case improvement 
Prior to latest update bbc had an issue where single path text field with attributes wasn't parsed:
e.g. \<variable name="locations">1,2,3,4\</variable>
This seems to have been fixed in latest update.
To ensure this not to happen in future changes this test case has been added.
Run the tests.
There are no functional changes in this PR, and if this is already covered in some other test, we can just close this PR.
> Test for text with and without attributes
